name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-rltgoDzp0 --delete --no-perms --no-times --no-owner --exclude=/dist/ --exclude=/vendor/ --exclude=/node_modules/ --exclude=.env --exclude=.git"
          SOURCE: "./"
          REMOTE_HOST: "ec2-54-167-79-37.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html/dw2s5-Laravel/"

      # Novo passo de depuração
      - name: Debugging information
        run: |
          ls -al /var/www/html/dw2s5-Laravel/
          id ubuntu
          df -h
